GET http://localhost:8000


###
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}


###
POST http://localhost:8000/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin123"
}